server:
  port: 9527
  servlet:
    context-path: /equipment

#数据源配置
# 8.0数据库需要设置时区 serverTimezone
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/equipment?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  servlet:
    multipart:
      max-file-size: 500MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#Mybatis配置
mybatis:
  # mapper文件的位置
  mapper-locations: classpath:mappers/*.xml
  # 配置Mybatis对应实体类的包名
  type-aliases-package: com.sy.equipmentserver.pojo

#自定义图片的存储位置
custom:
  #文件在磁盘上的存储位置
  fileDir: D:\\upload_img\\
  imgPath: /img/**
